### ISSUE TITLE
Malformed class name rt6

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1089]
```
Caused by: java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Unknown Source)
	at org.powerbot.bot.AuX.toString(wg:246)
	at org.powerbot.bot.nUl.null(wg:283)
	at org.powerbot.bot.nUl.null(wg:154)
	at org.powerbot.bot.rt6.client.Client.getWidgets(j:265)
	at org.powerbot.script.rt6.Widget.null(zb:275)
	at org.powerbot.script.rt6.Widget.component(zb:71)
	at org.powerbot.script.rt6.Widgets.component(lb:171)
```

**Comment by Timer** [comment]
```
Caused by: java.lang.InternalError: Malformed class name
    at java.lang.Class.getSimpleName(Unknown Source)
    at org.powerbot.bot.Reflector$FieldConfig.toString(Reflector.java:44)
    at org.powerbot.bot.Reflector.isTypeOf(Reflector.java:126)
    at org.powerbot.bot.Reflector.isTypeOf(Reflector.java:113)
    at org.powerbot.bot.rt6.client.Client.getWidgets(Client.java:253)
    at org.powerbot.script.rt6.Widget.getInternalComponents(Widget.java:87)
    at org.powerbot.script.rt6.Widget.component(Widget.java:58)
    at org.powerbot.script.rt6.Widgets.component(Widgets.java:78)
```

**Comment by Timer** [comment]
Should be fixed now.
