### ISSUE TITLE
Malformed class name

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1197]
```
java.lang.InternalError: Malformed class name 
	org.powerbot.bot.auX.toString(ej:243)
	org.powerbot.bot.COn.try(ej:46)
	org.powerbot.bot.COn.try(ej:263)
	org.powerbot.bot.COn.try(ej:184)
	org.powerbot.bot.rt6.client.RenderableNode.getEntity(ch:203)
	org.powerbot.script.rt6.Objects.get(pc:319)
	org.powerbot.script.rt6.Objects.get(pc:71)
	org.powerbot.script.rt6.Objects.get(pc:329)
	org.powerbot.script.AbstractQuery$1.initialValue(bb:223)
	org.powerbot.script.AbstractQuery$1.initialValue(bb:28)
	org.powerbot.script.AbstractQuery.select(bb:82)
```

**Comment by ArtificialPB** [comment]
Another one:
```
java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Unknown Source)
	at org.powerbot.bot.NUL.toString(gj:52)
	at org.powerbot.bot.AUX.byte(gj:9)
	at org.powerbot.bot.AUX.byte(gj:199)
	at org.powerbot.bot.rt6.client.Client.getWidgets(i:81)
	at org.powerbot.script.rt6.Widget.byte(vb:252)
	at org.powerbot.script.rt6.Widget.components(vb:352)
```
```
[INFO] Bot: Hash: b90c8dd348384df49b7511b28c14cf6006b6be64 size: 1245
```

**Comment by ArtificialPB** [comment]
And another one:
```
Caused by: java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Unknown Source)
	at org.powerbot.bot.nuL.toString(dh:217)
	at org.powerbot.bot.Con.long(dh:142)
	at org.powerbot.bot.Con.long(dh:285)
	at org.powerbot.bot.Con.long(dh:151)
	at org.powerbot.bot.rt6.client.Tile.getBoundary2(nj:177)
	at org.powerbot.bot.rt6.auX.long(dk:23)
	at org.powerbot.bot.rt6.auX.long(dk:311)
	at org.powerbot.script.rt6.Movement.collisionMap(yc:230)
	at org.powerbot.script.rt6.Movement.collisionMap(yc:27)
```

**Comment by Paris** [comment]
@Timer 
```
Caused by: java.lang.InternalError: Malformed class name
    at java.lang.Class.getSimpleName(Unknown Source)
    at org.powerbot.bot.Reflector$FieldConfig.toString(Reflector.java:44)
    at org.powerbot.bot.Reflector.isTypeOf(Reflector.java:126)
    at org.powerbot.bot.Reflector.isTypeOf(Reflector.java:113)
    at org.powerbot.bot.Reflector.isTypeOf(Reflector.java:109)
    at org.powerbot.bot.rt6.client.Tile.getBoundary2(Tile.java:36)
    at org.powerbot.bot.rt6.Map.readCollision(Map.java:117)
    at org.powerbot.bot.rt6.Map.readCollision(Map.java:66)
    at org.powerbot.script.rt6.Movement.collisionMap(Movement.java:199)
    at org.powerbot.script.rt6.Movement.collisionMap(Movement.java:195)
```

**Comment by Timer** [comment]
fixed
