### ISSUE TITLE
java.lang.NegativeArraySizeException on rt4 npcs

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1317]
```
java.lang.NegativeArraySizeException
    at z.TB.else(wo:257)
    at z.TB.<init>(wo:165)
    at z.LPT2.else(gk:71)
    at org.powerbot.script.rt4.CacheNpcConfig.else(id:210)
    at org.powerbot.script.rt4.Npc.name(sc:97)
    at org.powerbot.bot.rt4.AUX.repaint(nj:114)
    at org.powerbot.script.PaintEvent.call(yf:293)
    at org.powerbot.bot.rt4.AUx.else(gm:10)
    at org.powerbot.bot.coN.else(gm:214)
    at z.coM7.run(zk:131)
    at java.lang.Thread.run(Thread.java:745)
```

When trying to use the NPC viewer in the rsbot toolbar, it causes the overlay to freeze, and prints this stack trace.

**Comment by Timer** [comment]
```java.lang.NegativeArraySizeException
    at org.powerbot.bot.cache.Block.init(Block.java:56)
    at org.powerbot.bot.cache.Block.<init>(Block.java:36)
    at org.powerbot.bot.cache.CacheWorker.init(CacheWorker.java:67)
    at org.powerbot.script.rt4.CacheNpcConfig.read(CacheNpcConfig.java:49)
    at org.powerbot.script.rt4.Npc.name(Npc.java:46)
    at org.powerbot.bot.rt4.DrawMobs.repaint(DrawMobs.java:32)
    at org.powerbot.script.PaintEvent.call(PaintEvent.java:55)
    at org.powerbot.bot.rt4.EventDispatcher.getType(EventDispatcher.java:144)
    at org.powerbot.bot.EventDispatcher.getType(EventDispatcher.java:48)
    at org.powerbot.gui.BotOverlay$2.run(BotOverlay.java:197)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Timer** [comment]
This is a rare occurrence on a corrupted cache. Like stated previously, this error is caught and debugged. The reason it froze is probably because it's pulling tons of data from disk.
Will look into it more.

**Comment by achung205** [comment]
im having the same issue i believe:

```
java.lang.NegativeArraySizeException
	at z.TB.else(wo:257)
	at z.TB.<init>(wo:165)
	at z.LPT2.else(gk:71)
	at org.powerbot.script.rt4.CacheNpcConfig.else(id:210)
	at org.powerbot.script.rt4.Npc.actions(sc:58)
	at org.powerbot.script.Actionable$Matcher.accept(m:35)
	at org.powerbot.script.Actionable$Matcher.accept(m:303)
	at org.powerbot.script.AbstractQuery.select(zb:219)
	at org.powerbot.script.rt4.BasicQuery.action(dd)
	at org.powerbot.bot.rt4.aUX.else(ti:311)
	at org.powerbot.bot.rt4.aUX.poll(ti:242)
	at org.powerbot.script.PollingScript$6.run(mj:191)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
```

**Comment by ArtificialPB** [comment]
It happened with objects for me and it was fixed when I deleted osrs jagexcache. @Timer maybe add a dialog that shows to the users when this happens and let them know to delete their cache?

**Comment by ArtificialPB** [comment]
How do you decode OSRS Reference tables @Timer ? Can you show me a snippet of it?

**Comment by ArtificialPB** [comment]
When this happens, the script sometimes crashes with OutOfMemoryError:
```
java.lang.OutOfMemoryError: Java heap space 
	z.Db.if(dm:308)
	z.Db.<init>(dm:181)
	z.Lpt5.if(fp:131)
	org.powerbot.script.rt4.CacheObjectConfig.if(rd:204)
	org.powerbot.script.rt4.GameObject.name(dc:194)
	org.powerbot.script.Nameable$Matcher.accept(t:166)
	org.powerbot.script.Nameable$Matcher.accept(t:107)
	org.powerbot.script.AbstractQuery.select(wb:260)
	org.powerbot.script.rt4.BasicQuery.name(vd:187)
	org.powerbot.script.rt4.Bank.nearest(fd:210)
```

**Comment by Timer** [comment]
@ArtificialPB the code is identical to Method's (used with permission, of course)
https://gist.github.com/Timer/26fb7dabb082eb2f77308f14cf539514

**Comment by ArtificialPB** [comment]
Thanks @Timer . I've taken a look at it and it looks fine to me so I guess something else is causing this.

**Comment by ArtificialPB** [comment]
Another stack trace:
```
[SEVERE] java.lang.OutOfMemoryError: Java heap space 
	z.Ab.char(rn:94)
	z.Ab.<init>(rn:47)
	z.db.char(nf:164)
	org.powerbot.script.rt4.CacheNpcConfig.char(lc:124)
	org.powerbot.script.rt4.Npc.actions(vb:19)
	org.powerbot.script.Actionable$Matcher.accept(m:165)
	org.powerbot.script.Actionable$Matcher.accept(m:227)
	org.powerbot.script.AbstractQuery.select(ra:175)
	org.powerbot.script.rt4.BasicQuery.action(hc:233)
	org.powerbot.bot.rt4.CON.char(bi:86)
	org.powerbot.bot.rt4.CON.poll(bi:205)
	org.powerbot.script.PollingScript$6.run(wl:126)
```

**Comment by ChrisBPB** [comment]
@ArtificialPB @Moosheplusplus have you experienced this in the past year?
