### ISSUE TITLE
Script could not be downloaded

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1588]
Only happens for my OSRS scripts and it does not happen for everybody.
```
1050 Hash: 682d1a52eaf0523a26132d21c6a6548fbb5872e5 size: 234
1050 Select your game, then to play a script click Script > Play
1051 Could not download script (For input string: "lang/Object;")
1051 Could not download script (For input string: "lang/Object;") 
```

**Comment by ArtificialPB** [comment]
```
java.lang.NumberFormatException: For input string: "ow"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at z.prn.char(na:186)
    at z.prn.hasNext(na:201)
    at org.powerbot.bot.aUx.<init>(th:31)
    at z.auX.char(gj:116)
    at z.coM8.run(pm:410)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by ArtificialPB** [comment]
Fixed by clearing the repo and uploading the scripts again.

**Comment by AshGreh** [comment]
@ArtificialPB Problem still exists.

**Comment by ArtificialPB** [comment]
Apparently, the problem still occurs for some: https://www.powerbot.org/community/topic/1320346-acooker-os-complete-cooking-script-supports-all-items-at-many-different-locations/?page=8#comment-16312724

**Comment by ArtificialPB** [comment]
It also happens for RS3 scripts now.

**Comment by ArtificialPB** [comment]
```
2038 Could not download script (For input string: "*]??T???")
2038 java.lang.NumberFormatException: For input string: "*]??T???"
 at java.lang.NumberFormatException.forInputString(Unknown Source)
 at java.lang.Integer.parseInt(Unknown Source)
 at z.NUl.super(da:43)
 at z.NUl.hasNext(da:132)
 at org.powerbot.bot.aUx.<init>(in:139)
 at z.coN.if(ag:226)
 at z.com7.run(jm:262)
 at java.lang.Thread.run(Unknown Source) 
```

**Comment by Paris** [comment]
I've forced a rebuild, does this still happen?

**Comment by ArtificialPB** [comment]
Haven't received any reports today yet, I'll let you know if I do.

**Comment by ArtificialPB** [comment]
Haven't received any new reports. Users are now experiencing _NoClassDefFoundError_: #1586

**Comment by ArtificialPB** [comment]
Just happened again, the stack trace is the same as the one above.

**Comment by Paris** [comment]
After a series of updates to the SDN I forced a rebuild and tested [ACooker OS](https://www.powerbot.org/community/topic/1320346-acooker-os-complete-cooking-script-supports-all-items-at-many-different-locations/) and [ASlayer OS](https://www.powerbot.org/community/topic/1316277-aslayer-os-complete-slaying-script-supporting-all-slayer-masters-tasks-and-more/), both seem to load fine now.

**Comment by ArtificialPB** [comment]
Thanks @Paris.

**Comment by AshGreh** [comment]
Request you to re-open this.
The latest error log(which was today) is:
java.lang.NoClassDefFoundError: rhb 
	org.powerbot.bot.COn.run(ScriptController.java:151)

**Comment by ArtificialPB** [comment]
Seems to be happening again, here's the new stacktrace in v7041:
```
Could not download script java.lang.NumberFormatException: For input string: "W?_?8??_u?"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at z.Nul.byte(TarReader.java:68)
    at z.Nul.hasNext(TarReader.java:32)
    at org.powerbot.bot.nUL.<init>(ScriptClassLoader.java:32)
    at z.Prn.void(ScriptList.java:244)
    at z.cOm9.run(BotPreferences.java:388)
    at java.lang.Thread.run(Unknown Source) 
```
