### ISSUE TITLE
Config missing for getLoggerEntries

### ISSUE THREAD

**Issue by benpoulson** [powerbot/powerbot#1985]
**OS:** Mac OS 10.14 (18A391)
**Java:** 1.8.0_191
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
**RSBot Version:** RSBot-7082
**Program Arguments:** runescape
**jagexappletviewer.jar:** Latest

**VM Options:** 
```
-Djava.search.path=out
-Dcom.jagex.config=http://oldschool.runescape.com/l=en/jav_config.ws
-javaagent:"/home/ben/rsbot/RSBot.jar"
-Dsun.java2d.nodraw=true
-Xmx512m
-Xss2m
-XX:CompileThreshold=1500
-Xincgc
-XX:+UseConcMarkSweepGC
-XX:+UseParNewGC
-Xdock:name=RSBot
```

**Error:**
```
java.lang.RuntimeException: Config missing for getLoggerEntries
	at org.powerbot.bot.Reflector.this(Reflector.java:222)
	at org.powerbot.bot.Reflector.access(Reflector.java:113)
	at org.powerbot.bot.Reflector.access(Reflector.java:109)
	at org.powerbot.bot.rt4.client.Client.getLoggerEntries(Client.java:382)
	at org.powerbot.script.rt4.Chat$1.repaint(Chat.java:61)
	at org.powerbot.script.PaintEvent.call(PaintEvent.java:55)
	at org.powerbot.bot.rt4.EventDispatcher.this(EventDispatcher.java:131)
	at org.powerbot.bot.EventDispatcher.consume(EventDispatcher.java:43)
	at org.powerbot.gui.com3.this(BotOverlay.java:181)
	at java.lang.Thread.run(Thread.java:748)
[SEVERE] Exception: java.lang.RuntimeException: Config missing for getMenuActions 
	org.powerbot.bot.Reflector.this(Reflector.java:222)
	org.powerbot.bot.Reflector.access(Reflector.java:113)
	org.powerbot.bot.rt4.client.Client.getMenuActions(Client.java:194)
	org.powerbot.script.rt4.Menu.lambda$register$0(Menu.java:256)
```

Occurs as soon as RSBot starts rending the OSRS Login Screen. Not attempted RS3 yet.
No scripts built or presented to RSBot.

Breaking - Unable to run any scripts.

**Comment by ChrisBPB** [comment]
Thanks, will be fixed in around 4-5hours

**Comment by benpoulson** [comment]
@ChrisBPB You're the best. Shout if you need any more information.
