### ISSUE TITLE
SecurityException: setContextClassLoader when using HTTP GET

### ISSUE THREAD

**Issue by Mkerian10** [powerbot/powerbot#1992]
Downloading a json file off of my server causes an exception. Here's the stack trace:

```
java.lang.SecurityException: setContextClassLoader
	at org.powerbot.Aux.checkPermission(Sandbox.java:48)
	at java.lang.Thread.setContextClassLoader(Unknown Source)
	at sun.net.www.http.KeepAliveCache$1.run(Unknown Source)
	at sun.net.www.http.KeepAliveCache$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.http.KeepAliveCache.put(Unknown Source)
	at sun.net.www.http.HttpClient.putInKeepAliveCache(Unknown Source)
	at sun.net.www.http.HttpClient.finished(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.closeUnderlying(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.processRaw(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.readAheadBlocking(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.readAhead(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at s.z.A(NetworkUtils.java:60)
	at s.z.A(NetworkUtils.java:47)
	at s.SC.C(SpyderGraph.java:33)
	at s.lA.G(STScript.java:87)
	at java.lang.Thread.run(Unknown Source)
```

The actual line that seems to be causing the issue is: https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/sun/net/www/http/KeepAliveCache.java#L111

I've tried multiple ways of reading the input stream from the URLConnection. None of them have worked, I either get the exception on collecting my stream, or BufferedInputStreamReader#readLine. This is a mostly isolated error, I've had it pop up only one time before this.

Here's the source for the NetworkUtils file.

```java
public static String GET(URL url) throws Exception{
		HttpURLConnection conn = (HttpURLConnection) url.openConnection();
		
		conn.setRequestMethod("GET");
		conn.setDoOutput(true);
		conn.setDoInput(true);
		conn.connect();
		
		if(conn.getResponseCode() == HttpURLConnection.HTTP_OK){
			String s = readStream(conn.getInputStream()); //Line 47
			conn.getInputStream().close();
			return s;
		}else{
			Logger.warning("NON-200 HTTP CONNECTION! " + conn.getResponseMessage());
			return conn.getResponseCode() + " INVALID CONNECTION!";
		}
	}
	
	public static String readStream(InputStream inputStream) throws IOException{
		StringBuilder sb = new StringBuilder();
		BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
		
		String curr = reader.readLine(); // Line 60
		while(curr != null){
			sb.append(curr);
			curr = reader.readLine();
		}
		return sb.toString();
	}
```

**Comment by benpoulson** [comment]
Without knowing much of the internals, I can recommend using either:
* Statically accessing `org.powerbot.util.HttpUtils` for a HttpUrlConnection
* Using java.net.HttpURLConnection instead of the `sun.net.www` implementation.

**Comment by benpoulson** [comment]
Found the fix; Add:
`conn.setRequestProperty("Connection", "close");`
After you initialise `HttpURLConnection conn;`
