### ISSUE TITLE
GeItem/Download string isn't working

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#2058]
java.net.UnknownHostException: http
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1040)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1038)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1037)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
	at tests.GEItemTest.openStream(GEItemTest.java:218)
	at tests.GEItemTest.openStream(GEItemTest.java:212)
	at tests.GEItemTest.start(GEItemTest.java:40)
	at org.powerbot.script.PollingScript$2.run(PollingScript.java:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by benpoulson** [comment]
Error is at:
```		String url = "http://services" + Environment.DOMAINS[1] + "/m=itemdb_" + db + "/api/catalogue/detail.json?item=" + id;```

Missing "." after services

**Comment by benpoulson** [comment]
Also broken here

https://github.com/powerbot/powerbot/blob/161d00394b9f88d0c25aff9281e1f5a74c249253/src/main/java/org/powerbot/script/rt6/Hiscores.java#L21

**Comment by ChrisBPB** [comment]
https://github.com/powerbot/powerbot/pull/2059
