### ISSUE TITLE
Banking broken

### ISSUE THREAD

**Issue by iicryptic** [powerbot/powerbot#2075]
Running the following :
```     
ctx.bank.open();
```
causes:
```
Started
13:07 scripts.main: null
java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at org.powerbot.script.rt4.BasicQuery.viewable(BasicQuery.java:185)
	at org.powerbot.script.rt4.Bank.getBank(Bank.java:38)
	at org.powerbot.script.rt4.Bank.open(Bank.java:105)
	at scripts.main.poll(main.java:28)
	at org.powerbot.script.PollingScript$1.run(PollingScript.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type interface org.powerbot.script.Locatable; not a subtype of implementation type interface org.powerbot.script.Viewable
	at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:233)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
	... 10 more
```

RSBot/7106 (X11; Linux x86_64) Java/1.8.0_212 [#4; 768 MiB]

**Comment by AshGreh** [comment]
Issue is being caused due to viewable, so anything using viewable should face this stack trace.

**Comment by AshGreh** [comment]
Seems like a problem with how Viewport::inViewport is handled through the obfuscator( I have faced something similar with the SDN before when using static references for predicates ).A possible solution would be to change back to npc->npc.inViewport() over static referencing.

**Comment by Paris** [comment]
Thanks this has been fixed in 7107.
