### ISSUE TITLE
Security exception writing to temp folder

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#2077]
`22:40 Script: bootstrap
java.lang.SecurityException
    at org.powerbot.Sandbox.checkPermission(Sandbox.java:70)
    at java.base/java.lang.SecurityManager.checkWrite(SecurityManager.java:838)
    at java.base/java.io.File.mkdir(File.java:1323)
    at java.base/java.io.File.mkdirs(File.java:1355)
    at java.base/java.io.File.mkdirs(File.java:1366)
    at org.powerbot.script.AbstractScript.getStorageDirectory(AbstractScript.java:168)
    at s.XC.E(AntibanFactory.java:82)
    at s.XC.a(AntibanFactory.java:15)
    at s.P.<init>(MrKrabs.java:48)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
    at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
    at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404)
    at java.base/java.lang.Class.newInstance(Class.java:590)
    at org.powerbot.bot.ScriptController$ScriptBootstrap.run(ScriptController.java:144)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:835)`

**Comment by benpoulson** [comment]
What operating system are you encountering this on?

And also what directory are you attempting to mkdir in?

**Comment by tanlines** [comment]
Was reported by a user. The folder is the temp folder returned by getStorageDirectory().

Startup: RSBot/7107 (Windows NT 10.0; WOW64﻿) Java/12.0.2 [#12; 4084 MiB]

**Comment by Paris** [comment]
I just tested and this shouldn't be happening, can you show your `File` constructor so I can check you're using the correct whitelisted path.

**Comment by tanlines** [comment]
User changed their java install directory and it worked.
