### ISSUE TITLE
Sandbox: Creating class loader denied

### ISSUE THREAD

**Issue by iampwningyou** [powerbot/powerbot#789]
Getting errors within the `org.powerbot.con.checkCreateClassLoader` method when starting the script after stopping the script. Happens usually after the 3rd time I stop the script.

https://github.com/iampwningyou/Flour-Runner

Tracelog:
```
[INFO] Script[WARNING] Script: The script will automatically stop after 1 hour. Apply for a developer account for extended time.
: Starting Flour Runner
[SEVERE] Sandbox: Creating class loader denied
java.lang.SecurityException
	at org.powerbot.con.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.<init>(Unknown Source)
	at sun.reflect.DelegatingClassLoader.<init>(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.ClassDefiner.defineClass(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
	at sun.reflect.MethodAccessorGenerator.generateConstructor(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.powerbot.bot.CON.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[SEVERE] Sandbox: Creating class loader denied
java.lang.SecurityException
	at org.powerbot.con.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.<init>(Unknown Source)
	at sun.reflect.DelegatingClassLoader.<init>(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.ClassDefiner.defineClass(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
	at sun.reflect.MethodAccessorGenerator.generateConstructor(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.powerbot.bot.CON.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[SEVERE] Sandbox: Creating class loader denied
java.lang.SecurityException
	at org.powerbot.con.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.<init>(Unknown Source)
	at sun.reflect.DelegatingClassLoader.<init>(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.ClassDefiner.defineClass(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
	at sun.reflect.MethodAccessorGenerator.generateConstructor(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.powerbot.bot.CON.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[SEVERE] Sandbox: Creating class loader denied
java.lang.SecurityException
	at org.powerbot.con.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.<init>(Unknown Source)
	at sun.reflect.DelegatingClassLoader.<init>(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.ClassDefiner.defineClass(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
	at sun.reflect.MethodAccessorGenerator.generateConstructor(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.powerbot.bot.CON.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
	at org.powerbot.bot.coN.do(Unknown Source)
	at org.powerbot.bot.coN.do(Unknown Source)
	at org.powerbot.bot.AUx.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[SEVERE] Sandbox: Creating class loader denied
java.lang.SecurityException
	at org.powerbot.con.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.<init>(Unknown Source)
	at sun.reflect.DelegatingClassLoader.<init>(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.ClassDefiner.defineClass(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
	at sun.reflect.MethodAccessorGenerator.generateConstructor(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.powerbot.bot.CON.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Paris** [comment]
Fixed for the next version.
