### ISSUE TITLE
Movement#collisionMap() exception

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#893]
Calling the above method throws Security Exception and crashes the script. This is v7.

```
[SEVERE] Sandbox: Creating class loader denied
[SEVERE] java.lang.SecurityException 
	org.powerbot.con.checkCreateClassLoader(yh:57)
	org.powerbot.bot.rt6.AuX.if(zk:198)
	org.powerbot.bot.rt6.AuX.if(zk:53)
	org.powerbot.script.rt6.Movement.collisionMap(pc:142)
	org.powerbot.script.rt6.Movement.collisionMap(pc:202)
	com.artificial.scripts.testclass.Testing.poll(Testing.java:74)
	org.powerbot.script.PollingScript$6.run(km:53)
```

**Comment by k0na** [comment]
Verified

java.lang.SecurityException
	at org.powerbot.con.checkCreateClassLoader(yh:57)
	at java.lang.ClassLoader.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.<init>(Unknown Source)
	at sun.reflect.DelegatingClassLoader.<init>(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.ClassDefiner.defineClass(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
	at sun.reflect.MethodAccessorGenerator.generateMethod(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.powerbot.script.rt6.BasicObject.if(jd:74)
	at org.powerbot.script.rt6.BasicObject.getId(jd:138)
	at org.powerbot.script.rt6.GameObject.id(ic:168)
	at org.powerbot.bot.rt6.AuX.if(zk:137)
	at org.powerbot.bot.rt6.AuX.if(zk:108)
	at org.powerbot.script.rt6.Movement.collisionMap(pc:142)
	at org.powerbot.script.rt6.Movement.collisionMap(pc:202)
	at biz.k0na.scripts.Tester.poll(Tester.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.powerbot.bot.Nul.run(tj:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.SecurityException
	at org.powerbot.con.checkCreateClassLoader(yh:57)
	at java.lang.ClassLoader.checkCreateClassLoader(Unknown Source)
	at java.lang.ClassLoader.<init>(Unknown Source)
	at sun.reflect.DelegatingClassLoader.<init>(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at sun.reflect.ClassDefiner$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.ClassDefiner.defineClass(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
	at sun.reflect.MethodAccessorGenerator.generateMethod(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.powerbot.script.rt6.BasicObject.if(jd:74)
	at org.powerbot.script.rt6.BasicObject.getId(jd:138)
	at org.powerbot.script.rt6.GameObject.id(ic:168)
	at org.powerbot.bot.rt6.AuX.if(zk:137)
	at org.powerbot.bot.rt6.AuX.if(zk:108)
	at org.powerbot.script.rt6.Movement.collisionMap(pc:142)
	at org.powerbot.script.rt6.Movement.collisionMap(pc:202)
	at biz.k0na.scripts.Tester.poll(Tester.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.powerbot.bot.Nul.run(tj:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Timer** [comment]
Fixed.
