### ISSUE TITLE
Movement#collisionMap() throws IllegalArgumentException

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#933]
```java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.FileChannelImpl.readInternal(Unknown Source)
	at sun.nio.ch.FileChannelImpl.read(Unknown Source)
	at z.LA.null(cg:33)
	at z.T.null(hj:75)
	at org.powerbot.script.rt6.CacheObjectConfig.null(jd:33)
	at org.powerbot.script.rt6.GameObject.clippingType(jc:166)
	at org.powerbot.bot.rt6.CoN.null(wo:82)
	at org.powerbot.bot.rt6.CoN.null(wo:14)
	at org.powerbot.script.rt6.Movement.collisionMap(kc:115)
	at org.powerbot.script.rt6.Movement.collisionMap(kc:139)
```

**Comment by Timer** [comment]
Always or randomly?

**Comment by ArtificialPB** [comment]
Randomly

**Comment by Timer** [comment]
This is probably happening because jagex is writing to the cache as rsbot is fetching from it.

**Comment by ArtificialPB** [comment]
I'll handle the error appropriately then.

I'll leave it up to you to decide if you'll close this issue or not.

**Comment by Timer** [comment]
I'll take care of it just brainstorming.

**Comment by ArtificialPB** [comment]
Another exception when calling the above method:
```
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Unknown Source)
	at java.nio.DirectByteBuffer.getShort(Unknown Source)
	at z.LA.null(cg:205)
	at z.T.null(hj:75)
	at org.powerbot.script.rt6.CacheObjectConfig.null(jd:33)
	at org.powerbot.script.rt6.GameObject.clippingType(jc:166)
	at org.powerbot.bot.rt6.CoN.null(wo:82)
	at org.powerbot.bot.rt6.CoN.null(wo:14)
	at org.powerbot.script.rt6.Movement.collisionMap(kc:115)
	at org.powerbot.script.rt6.Movement.collisionMap(kc:139)
```

**Comment by Timer** [comment]
Please get me this with 7003.

**Comment by ArtificialPB** [comment]
Here you go
```
java.lang.ExceptionInInitializerError
	at org.powerbot.bot.rt6.aux.void(al:313)
	at org.powerbot.bot.rt6.aux.void(al:138)
	at org.powerbot.script.rt6.Movement.collisionMap(hc:166)
	at org.powerbot.script.rt6.Movement.collisionMap(hc:338)
Caused by: java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.FileChannelImpl.readInternal(Unknown Source)
	at sun.nio.ch.FileChannelImpl.read(Unknown Source)
	at z.ic.void(jh:287)
	at z.wB.void(kj:275)
	at z.wB.<init>(kj:342)
	at org.powerbot.script.rt6.GameObject.<clinit>(qc:269)
	... 15 more
```

**Comment by Timer** [comment]
Placing this so I don't lose it.

```
java.lang.ExceptionInInitializerError
    at org.powerbot.bot.rt6.Map.readCollision(Map.java:105)
    at org.powerbot.bot.rt6.Map.readCollision(Map.java:65)
    at org.powerbot.script.rt6.Movement.collisionMap(Movement.java:196)
    at org.powerbot.script.rt6.Movement.collisionMap(Movement.java:192)
Caused by: java.lang.IllegalArgumentException
    at java.nio.Buffer.position(Unknown Source)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
    at sun.nio.ch.IOUtil.read(Unknown Source)
    at sun.nio.ch.FileChannelImpl.readInternal(Unknown Source)
    at sun.nio.ch.FileChannelImpl.read(Unknown Source)
    at org.powerbot.bot.cache.FileStore.getMediumInt(FileStore.java:67)
    at org.powerbot.bot.cache.CacheWorker.init(CacheWorker.java:27)
    at org.powerbot.bot.cache.CacheWorker.<init>(CacheWorker.java:15)
    at org.powerbot.script.rt6.GameObject.<clinit>(GameObject.java:18)
    ... 15 more

java.lang.NoClassDefFoundError: Could not initialize class org.powerbot.script.rt6.GameObject
    at org.powerbot.bot.rt6.Map.readCollision(Map.java:105)
    at org.powerbot.bot.rt6.Map.readCollision(Map.java:65)
    at org.powerbot.script.rt6.Movement.collisionMap(Movement.java:196)
    at org.powerbot.script.rt6.Movement.collisionMap(Movement.java:192)
```

**Comment by Timer** [comment]
Should've taken care of that.
