### ISSUE TITLE
Obfuscation breaks Serializable classes

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#961]
Not sure if this is intentional or not, but it seems the bot is unable to deserialize classes once the script is on the SDN and its source is obfuscated.
Here's the error:
```
java.lang.ClassNotFoundException: com.artificial.framework.wrappers.SkillRequirement
	at java.lang.ClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.powerbot.bot.COn.loadClass(gg:348)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at java.io.ObjectInputStream.resolveClass(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readArray(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at xgb.a(xgb.java:37)
	at ygb.run(ygb.java:27)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
If this is intentional I can change my code to work without serialization of classes.

**Comment by Paris** [comment]
You need to have a static reference to the class in your main script by having some dummy code in there so the obfuscator doesn't opportunistically remove it.
