### ISSUE TITLE
Client not drawing to screen, clicking methods arent working

### ISSUE THREAD

**Issue by tomHaum** [powerbot/powerbot#972]
http://www.powerbot.org/community/topic/1285642-nothing-is-drawing-to-screen-scripts-arent-working/
I have client 7007. Java 6_u45 for 32 bit
It seems like the client is loaded to the point that it knows about the game objects because i can print item names and GamObjects and all sorts of things, but when i try to interact() or click() nothing happens
getting this error

```
[2015.10.05 09:23:08] (Coverage): Error during class instrumentation: client: java.lang.NullPointerException
[2015.10.05 09:23:08] (Coverage): Error during class instrumentation: ey: java.lang.NullPointerException
[2015.10.05 09:23:08] (Coverage): Error during class instrumentation: ex: java.lang.NullPointerException
Exception in thread "main" java.lang.NoClassDefFoundError: ba
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
    at java.lang.Class.getConstructor0(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at app.appletviewer.e(Unknown Source)
    at app.appletviewer.a(Unknown Source)
    at jagexappletviewer.main(jagexappletviewer.java:34)
Caused by: java.lang.ClassNotFoundException: ba
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at app.u.loadClass(u.java:79)
    at java.lang.ClassLoader.findSystemClass(Unknown Source)
    at app.aa.loadClass(aa.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 8 more
```

Is this a problem with the bot or the just runescape being dumb

**Comment by tomHaum** [comment]
Well i unistalled the base game and deleted all my jagexcaches and now it works...
